export const USERNAME_MIN_LENGTH = 3;
export const USERNAME_MAX_LENGTH = 250;
export const INVALID_SHORT_USERNAME = USERNAME_MIN_LENGTH - 1;
export const INVALID_LONG_USERNAME = USERNAME_MAX_LENGTH + 1;

export const PASSWORD_MIN_LENGTH = 8;
export const PASSWORD_MAX_LENGTH = 72; // bcrypt limit
export const INVALID_SHORT_PASSWORD = PASSWORD_MIN_LENGTH - 1;
export const INVALID_LONG_PASSWORD = PASSWORD_MAX_LENGTH + 1;